### PR TITLE
Edition 124

### PR DESCRIPTION
**Pull request by chiuki**

### CODE REVIEW

**Comment by chiuki** [comment]
Hi @yprabhu! We'll be working on the next issue via this PR. Please add links & inspiration by committing to this branch (`edition-124`). You can look at our [issues](https://github.com/catehstn/technically-speaking/issues) for things to include, or find them from the internet.

In the header we'll need your location and a quick intro. You can look at this PR for an example: #317 (and the corresponding issue: https://github.com/catehstn/technically-speaking/blob/master/2017/03-March/21.md)

Thanks!

**Comment by yprabhu** [comment]
Noting down interesting links as I find them:
Article based on the twitter call that was put out a couple of weeks ago: https://mic.com/articles/175136/women-in-tech-1000-names-no-more-all-male-panels-conferences#.nyF4SYa6D

**Comment by chiuki** [comment]
I'd like to include these reactions to the article you mentioned:
https://twitter.com/sarahjeong/status/859837698906783744
https://twitter.com/catehstn/status/859852364521537537

**Comment by yprabhu** [comment]
Yes!!! Those reactions are 💯  

On another note, looking through past issues, I see that only 3 CFPs are included per issue. Is that intentional?

**Comment by yprabhu** [comment]
Came across this - it's an oldie but still relevant http://www.presentationzen.com/presentationzen/2014/11/10-tips-for-improving-your-presentations-lectures-speeches.html

**Comment by chiuki** [comment]
Yup, max 3 CFPs per issue. We're doing curation, not exhaustive list, so we cap at 3.

**Pull request merged**
