### PR TITLE
initial commit of issue

### PR DESCRIPTION
**Pull request by catehstn**
Hey @larahogan this is the PR that we'll put your issue in :) 

If you look at #207 #208 #209 you'll see the other contributor issues. If you put together an intro (be sure to mention your book), and then you can curate whatever content you want to include. @chiuki will help you, add in anything extra, and send it out on Tuesday 21st via TinyLetter. Thanks! <3

### CODE REVIEW

**Comment by larahogan** [comment]
YAYYYY! Thanks, @catehstn! I will start adding links to articles with comments here. I'm not sure where to find CFPs - can @chiuki help with that? :D

**Comment by larahogan** [comment]
Oh I found this CFP for CSS Conf - https://docs.google.com/forms/d/e/1FAIpQLSflPzq54uyaAtGzcRS6U3om-t_AH3HMr1SGKbW99qREbKbxPw/viewform

**Comment by larahogan** [comment]
Should def talk about this thread: https://twitter.com/Luvvie/status/841714404731322370

**Comment by larahogan** [comment]
And maybe this for a laugh? https://twitter.com/fioroco/status/841044811583016961

**Comment by larahogan** [comment]
Two bits of inspiration:
https://www.yeseniaperezcruz.com/speaking/
https://rachelandrew.co.uk/speaking/

**Comment by chiuki** [comment]
Yay @larahogan! I've been collecting CFPs in our [issues](https://github.com/catehstn/technically-speaking/issues?q=is%3Aopen+is%3Aissue+label%3ACFP), and added CSS Dev Conf as #322. I'll pick a few to include in this issue.

https://twitter.com/Luvvie/status/841714404731322370 will be a great follow-up to the Storify (#290) we included on [February 21](https://github.com/catehstn/technically-speaking/blob/master/2017/02-February/14.md). There is also an article I'd like to include with that (#319). I'll write a blurb and put it in Link Roundup.

For the other links, go ahead and commit them to [03-March/21.md](https://github.com/catehstn/technically-speaking/blob/edition-117/2017/03-March/21.md) and we'll tweak them as we go along. If you want you can grab something from the [link issues](https://github.com/catehstn/technically-speaking/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20label%3ALink%20) and write blurbs for them as well. Thanks!

**Comment by larahogan** [comment]
Thanks, @chiuki!! Do you normally quote the original person who submitted the link? There's so much good stuff in #318 already written so I want to make sure I cite her correctly.

**Comment by chiuki** [comment]
Here is an example of how we credited the submitter for #229 with a HT: https://github.com/catehstn/technically-speaking/commit/efe9f99025514226d7621df66e18accbbf60aeeb

We've never seen a long submission like #318 so maybe we can link it back to the GitHub issue itself so people can see the source?

**Comment by larahogan** [comment]
@chiuki I think I'm all set - cleaned up the inspiration links, and also added a better book description at the top. Can I help with anything else?

**Comment by chiuki** [comment]
This looks good. I'll add the summary on top and send it out on Tuesday. Thanks @larahogan!

**Pull request merged**
